#!/bin/bash
# Manual USB HID setup commands
# Run these commands as root to enable POS forwarding

echo "Run these commands as root to enable USB HID gadget:"
echo ""
echo "# Load USB gadget modules"
echo "modprobe dwc2"
echo "modprobe libcomposite"
echo ""
echo "# Create gadget directory"
echo "cd /sys/kernel/config/usb_gadget/"
echo "mkdir -p caleffi_scanner"
echo "cd caleffi_scanner"
echo ""
echo "# Set gadget attributes"
echo "echo 0x1d6b > idVendor"
echo "echo 0x0104 > idProduct" 
echo "echo 0x0100 > bcdDevice"
echo "echo 0x0200 > bcdUSB"
echo ""
echo "# Create strings"
echo "mkdir -p strings/0x409"
echo "echo 'Caleffi' > strings/0x409/manufacturer"
echo "echo 'Barcode Scanner HID' > strings/0x409/product"
echo "echo '123456789' > strings/0x409/serialnumber"
echo ""
echo "# Create HID function"
echo "mkdir -p functions/hid.usb0"
echo "echo 1 > functions/hid.usb0/protocol"
echo "echo 1 > functions/hid.usb0/subclass"
echo "echo 8 > functions/hid.usb0/report_length"
echo ""
echo "# Set HID report descriptor"
echo "echo -ne '\\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0' > functions/hid.usb0/report_desc"
echo ""
echo "# Create configuration"
echo "mkdir -p configs/c.1/strings/0x409"
echo "echo 'Config 1: HID Keyboard' > configs/c.1/strings/0x409/configuration"
echo "echo 250 > configs/c.1/MaxPower"
echo ""
echo "# Link function to configuration"
echo "ln -sf /sys/kernel/config/usb_gadget/caleffi_scanner/functions/hid.usb0 /sys/kernel/config/usb_gadget/caleffi_scanner/configs/c.1/"
echo ""
echo "# Enable gadget"
echo "UDC=\$(ls /sys/class/udc | head -1)"
echo "echo \$UDC > UDC"
echo ""
echo "# Set permissions"
echo "chmod 666 /dev/hidg0"
echo ""
echo "After running these commands, /dev/hidg0 should exist and POS forwarding will work!"
